### ISSUE TITLE
upgrade to node16 

### ISSUE THREAD

**Issue by jcaramescision** [stCarolas/setup-maven#29]
Error from GitHub actions.
`Node.js 12 actions are deprecated. 
For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: stCarolas/setup-maven`

**Comment by stCarolas** [comment]
Released in https://github.com/stCarolas/setup-maven/releases/tag/v.4.5
