### ISSUE TITLE
Consider unsetting or modifying M2_HOME

### ISSUE THREAD

**Issue by famod** [stCarolas/setup-maven#7]
Ubuntu and probably other virtual GH environments come with `M2_HOME` preset.
This breaks Maven versions lower than 3.5.0 that are installed with this action from working properly.
I have written down the details in https://github.com/actions/virtual-environments/issues/2534.

So, as a workaround for that issue, I thought that maybe this action could at least unset `M2_HOME`?
Next best thing would be to modify `M2_HOME` to point to the right Maven installation but then again: it shouldn't be used at all anymore...

**Comment by stCarolas** [comment]
I think setting `M2_HOME` to right installation more expected thing than unsetting. Also seems like correct for situation with installing old maven into environment with another old maven.

**Comment by famod** [comment]
The virtual-environments issue was already assigned, so maybe the root cause will be fixed sooner than expected and we don't need a workaorund.

If you choose to set M2_HOME even for Maven 3.5.0+ then people are less motivated to let go of that removed property, just saying...

**Comment by famod** [comment]
The fix for https://github.com/actions/virtual-environments/issues/2534 was rolled out, so M2_HOME is not present anymore.

So for me this topic is done.
